cache:
  directories:
    -  $HOME/.m2

language: java

services:
  -  docker

stages:
  -  test
  -  deploy

install: skip

jobs:
  include:
    -  stage: test
      name: "Testing Application"
      services: postgresql